### Day 9

We're given a large grid of numbers and are asked to find the "low points" which are cells with a smaller value than all their adjacent (not diagonal) neighbors. We're asked to sum up 1+ the values on all these low points

In [24]:
import pandas as pd
import numpy as np

with open('d9.txt') as file:
    puzzle_input = file.readlines()
    
vents = [x.strip() for x in puzzle_input]
vents = [[int(y) for y in x] for x in vents]
vents = np.array(vents)
vents

array([[8, 6, 5, ..., 9, 9, 9],
       [8, 7, 4, ..., 8, 7, 7],
       [9, 6, 5, ..., 9, 5, 6],
       ...,
       [8, 7, 6, ..., 1, 2, 3],
       [9, 8, 9, ..., 3, 4, 4],
       [9, 9, 6, ..., 4, 6, 7]])

Trying to think about what could be done to speed this up... I don't think it will be particularly slow to just run through every cell but seems like there should be some neat trick....

Only thing I'm thinking of is marking the adjacent cells as NOT minimums when we do find a min... but that probably requires enough other checks that it's not worth it....

In [53]:
# store the results here
mins = np.zeros(shape = vents.shape)

shifts = [(-1, 0), (0, 1), (1, 0), (0, -1)]

for i in range(vents.shape[0]):
    for j in range(vents.shape[1]):
        
        cell_value = vents[i][j]
        
        comparisons = []
        for shift in shifts:
            
            next_row = i + shift[0]
            next_col = j + shift[1]
            
            if (next_row >= 0) and (next_row < 100) and (next_col >= 0) and (next_col < 100):
                comparisons.append(vents[next_row][next_col])
                
        
        if cell_value < min(comparisons):
            mins[i][j] = cell_value + 1
        

mins.sum()       
        

439.0

In [54]:
mins

array([[0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       ...,
       [0., 0., 0., ..., 2., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.]])

In [28]:
mins.shape

(100, 100)

In [30]:
try:
    vents[-1][0]
    print('bonk')
except KeyError:
    print('conk')

bonk


In [32]:
vents[-1]

array([9, 9, 6, 5, 4, 1, 0, 9, 8, 7, 3, 2, 1, 0, 2, 4, 5, 8, 9, 9, 9, 9,
       8, 9, 9, 9, 9, 8, 7, 6, 5, 6, 7, 6, 8, 9, 1, 2, 9, 9, 8, 7, 6, 5,
       3, 5, 6, 7, 8, 9, 7, 5, 3, 2, 4, 6, 6, 7, 8, 9, 7, 6, 4, 3, 2, 4,
       5, 6, 9, 8, 8, 6, 7, 6, 8, 6, 7, 8, 9, 2, 1, 0, 1, 2, 3, 4, 5, 6,
       8, 9, 2, 3, 7, 8, 9, 5, 4, 4, 6, 7])